version: "3"

services:

  signup-postgres:
    image: postgres:11
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    expose:
      - "${DB_PORT}"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"


  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
     - "signup-postgres"
    command: "signup-postgres:${DB_PORT}"

  signup:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    volumes:
      - ./src:/vol/app/src
      - ./lib:/vol/app/lib
    ports:
      - "8000:8000"
    environment:
      - DB_VENDOR
      - DB_HOST
      - DB_PORT
      - DB_PASSWORD
      - DB_USER
      - DB_NAME
      - PYTHONDONTWRITEBYTECODE=yes
      - NOSE_INCLUDE_EXE=1
      - DJANGO_SETTINGS_MODULE=signup.dev_settings
    depends_on:
      - "start_dependencies"
